version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/discord"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/plugin"
    schedule:
      interval: "daily"
