locale: "en"

reminder:
  delay: 5
  repeat: 15

discord:
  enabled: false
  guild: ""
  token: ""

alias:
  create: "create|c"
  update: "update|u"
  close: "close|cl"
  show: "show|s"
  pick: "pick|p"
  assign: "assign|a"
  done: "done|d"
  yield: "yield|y"
  note: "note"
  reopen: "reopen|ro"
  teleport: "teleport|tp"
  log: "log"
  list: "list|l"
  status: "status"
