name: PureTickets
main: co.uk.magmo.puretickets.PureTickets
version: 2.4.0
api-version: 1.13

permissions:
  tickets.user.*:
    default: true
    description: Allows access to all ticket user permissions
    children:
      tickets.user: true
      tickets.user.create: true
      tickets.user.update: true
      tickets.user.settings: true
      tickets.user.close: true
      tickets.user.show: true
      tickets.user.list: true
      tickets.user.log: true
  tickets.user.create:
    default: true
    description: Allows a user to create a ticket
  tickets.user.update:
    default: true
    description: Allows a user to update a ticket
  tickets.user.settings:
    default: true
    description: Allows a user to manage their personal settings
  tickets.user.close:
    default: true
    description: Allows a user to close a ticket
  tickets.user.show:
    default: true
    description: Allows a user to close a ticket
  tickets.user.list:
    default: true
    description: Allows a user to close a ticket
  tickets.user.log:
    default: true
    description: Allows a user to close a ticket
  tickets.staff.*:
    default: op
    description: Allows access to all ticket staff permissions
    children:
      tickets.staff: true
      tickets.user.show: true
      tickets.user.pick: true
      tickets.user.assign: true
      tickets.user.done: true
      tickets.user.yield: true
      tickets.user.reopen: true
      tickets.user.teleport: true
      tickets.user.log: true
      tickets.user.list: true
      tickets.user.announce: true
      tickets.user.remind: true
      tickets.user.reload: false
  tickets.staff.show:
    default: op
    description: Allows a user to view a ticket
  tickets.staff.pick:
    default: op
    description: Allows a user to pick a ticket
  tickets.staff.assign:
    default: op
    description: Allows a user to assign a ticket to someone
  tickets.staff.done:
    default: op
    description: Allows a user to done-mark a ticket
  tickets.staff.yield:
    default: op
    description: Allows a user to yield a ticket
  tickets.staff.reopen:
    default: op
    description: Allows a user to reopen a ticket
  tickets.staff.teleport:
    default: op
    description: Allows a user to teleport to a ticket
  tickets.staff.log:
    default: op
    description: Allows a user to view a tickets messages
  tickets.staff.list:
    default: op
    description: Allows a user to view all open tickets
  tickets.staff.announce:
    default: op
    description: Allows a user to see when a ticket is changed
  tickets.staff.remind:
    default: op
    description: Allows a user to view the ticket reminder message
  tickets.staff.reload:
    default: op
    description: Allows a user to reload parts of tickets